input CreateSpeciesInput {
    scientificName: String!
    commonName: String
    family: String
    genus: String
    distributionNotes: String
    description: String
    status: Status!
    imageUrl: String
}

input UpdateSpeciesInput {
    scientificName: String
    commonName: String
    family: String
    genus: String
    distributionNotes: String
    description: String
    status: Status
    imageUrl: String
}

input CreateCoordinateInput {
    latitude: Float!
    longitude: Float!
    localityName: String
}