spring.application.name=robinson-fishoe

### DATABASE CONFIG ###

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/robinson-fishoe}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.show_sql=true
spring.jpa.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
### END DATABASE CONFIG ###

### GRAPHQL CONFIG ###
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

# GraphQL endpoint
spring.graphql.path=/graphql

# Schema locations (add this)
spring.graphql.schema.locations=classpath:graphql/
spring.graphql.schema.printer.enabled=true
### END GRAPHQL CONFIG ###